# Generated by Django 2.2.10 on 2021-07-13 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Time_record', models.DateTimeField(auto_now_add=True)),
                ('product_img1', models.ImageField(upload_to='uploads/products', verbose_name='Product Image 1')),
                ('product_img2', models.ImageField(upload_to='uploads/products', verbose_name='Product Image 2')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='latestProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Time_record', models.DateTimeField(auto_now_add=True)),
                ('latest_product_img', models.ImageField(upload_to='uploads/products', verbose_name='latest Product Image 1')),
                ('latest_prize', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('latest_product_description', models.TextField(blank=True, null=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_property_agent', to=settings.AUTH_USER_MODEL)),
                ('latest_product_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lat_property_cat', to='ecommerce_app.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='featureProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Time_record', models.DateTimeField(auto_now_add=True)),
                ('feature_product_img', models.ImageField(upload_to='uploads/feature product_img', verbose_name='Feature Product Image 1')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('feature_product_description', models.TextField(blank=True, null=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_product_agent', to=settings.AUTH_USER_MODEL)),
                ('feature_product_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_product_cat_id', to='ecommerce_app.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ContactAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='carousel_slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Time_record', models.DateTimeField(auto_now_add=True)),
                ('carousel_product_img', models.ImageField(upload_to='uploads/carousel product_img', verbose_name='carousel Product Image 1')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('carousel_product_description', models.TextField(blank=True, null=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_product_agent', to=settings.AUTH_USER_MODEL)),
                ('carousel_product_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_product_cat_id', to='ecommerce_app.ProductCategory')),
            ],
        ),
    ]
