# Generated by Django 3.1.1 on 2021-07-09 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_id', models.DecimalField(decimal_places=0, max_digits=90)),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Time_record', models.DateTimeField(auto_now_add=True)),
                ('product_img1', models.ImageField(blank=True, null=True, upload_to='uploads/products', verbose_name='Product Image 1')),
                ('product_img2', models.ImageField(blank=True, null=True, upload_to='uploads/products', verbose_name='Product Image 2')),
                ('product_img3', models.ImageField(blank=True, null=True, upload_to='uploads/products', verbose_name='Product Image 3')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('product_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
