# Generated by Django 2.2.10 on 2021-07-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestproduct',
            name='latest_discount_prize',
        ),
        migrations.AddField(
            model_name='contactagent',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
