# Generated by Django 2.2.10 on 2021-07-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(default=1, upload_to='uploads/products', verbose_name='Product Image 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(default='1', upload_to='uploads/products', verbose_name='Product Image 2'),
            preserve_default=False,
        ),
    ]
