# Generated by Django 2.2.10 on 2021-07-12 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_app', '0002_auto_20210712_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img2',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='latestProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Time_record', models.DateTimeField(auto_now_add=True)),
                ('latest_product_img', models.ImageField(upload_to='uploads/products', verbose_name='Product Image 1')),
                ('latest_prize', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('latest_product_description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_property_agent', to=settings.AUTH_USER_MODEL)),
                ('latest_product_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_location', to='ecommerce_app.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='featureProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Time_record', models.DateTimeField(auto_now_add=True)),
                ('feature_product_img', models.ImageField(upload_to='uploads/feature product_img', verbose_name='Feature Product Image 1')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('feature_product_description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_product_agent', to=settings.AUTH_USER_MODEL)),
                ('feature_product_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_product_cat_id', to='ecommerce_app.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ContactAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.ProductCategory')),
            ],
        ),
    ]
