# Generated by Django 2.2.10 on 2021-07-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_auto_20210712_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(default='01-12-2010', upload_to='uploads/products', verbose_name='Product Image 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latestproduct',
            name='latest_product_cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lat_property_cat', to='ecommerce_app.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='latestproduct',
            name='latest_product_img',
            field=models.ImageField(upload_to='uploads/products', verbose_name='latest Product Image 1'),
        ),
    ]
