# Generated by Django 2.2.10 on 2021-07-12 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_app', '0004_auto_20210712_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='latestproduct',
            name='name',
        ),
        migrations.CreateModel(
            name='carousel_slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Time_record', models.DateTimeField(auto_now_add=True)),
                ('carousel_product_img', models.ImageField(upload_to='uploads/carousel product_img', verbose_name='carousel Product Image 1')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('carousel_product_description', models.TextField(blank=True, null=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_product_agent', to=settings.AUTH_USER_MODEL)),
                ('carousel_product_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_product_cat_id', to='ecommerce_app.ProductCategory')),
            ],
        ),
    ]
